language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jonwehner/aws-test-deploy -f Dockerfile.dev ./.

script:
  - docker run -e CI=true jonwehner/aws-test-deploy npm run test
