language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jonwehner/aws-test-deploy -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true jonwehner/aws-test-deploy npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-875014098063'
  bucket_path: 'docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
